import DevTodayImage from '@/public/dev-today.png';

import {
  AbstractFlower,
  ArmadilloTails,
  AbstractFlowerProcess,
  Agape,
  BeehiveVase,
  BenchLines,
  Beowolf,
  BleedingBlues,
  BubbleVase1,
  BubbleVase2,
  Clothesline,
  ColoredTiles,
  ColorSplats,
  ColorSplats2,
  ColorSplatsDots,
  Crow,
  CrowProcess,
  CrowsSelfPortrait,
  Curlew,
  Day2Spider,
  Day4PipeWorms,
  Day5CityMoon,
  Flowers,
  FlyingGecko,
  GlazedPlates,
  FlyingGeckoProcess,
  HatGlazeware2,
  HeartSplatters,
  HouseLines,
  Jellyfish,
  Jellyfish2,
  KingCrownDiamonds,
  LandscapeHand,
  LittleMan,
  LittleManGlazed,
  LoopyManGlazed3,
  LoopyManProcess,
  ManLinesPaint,
  ManWithWeeds,
  Mask1,
  Mask2,
  MirrorMirror,
  PhonesRamen,
  QuizzicalFigure,
  RamenGlazeware1,
  RamenGlazeware2,
  SelfPortraitPaint,
  SpaceMan,
  SpaghettiPeople,
  SpillingOver,
  Toothbrush,
  TreesAndMountains,
  UndulatingPlanter,
  WormVase,
} from '@/public/art';

export const navbarItems = [
  {
    route: '/about',
    title: 'About',
  },
  {
    route: '/work',
    title: 'Work',
  },
  {
    route: '/projects',
    title: 'Projects',
  },
  {
    route: '/art',
    title: 'Art',
  },
];

export const workTabs = [
  {
    tabType: 'software',
    buttonText: 'Software Engineering',
  },
  {
    tabType: 'architecture',
    buttonText: 'Architecture',
  },
];

export const softwareWorkItems = [
  {
    date: 'Feb 2023 - May 2023',
    company: 'UStrive',
    description: 'An online career and college mentoring platform.',
    role: 'Full-stack Developer',
    details:
      'Developed and maintained mentor and student portals for an online mentoring platform – Debugged duplicate messages issue – Updated onboarding process in mixpanel to document user interaction ',
    website: 'https://ustrive.com/',
    tags: [
      'JavaScript',
      'Express',
      'Node.js',
      'React.js',
      'Axios',
      'Twilio',
      'Mixpanel',
      'Docker',
    ],
  },
  {
    date: 'May 2022 - Jan 2023',
    company: 'Mapistry',
    description:
      'An Environmental, Health, and Safety compliance SaaS platform and an early stage startup.',
    role: 'Full-stack Developer',
    details:
      'Contributed to the fullstack of the application around dynamic form generation for internal and external use – Implemented the migration of the existing functionality of the app to the new site using updated UX/UI designs and a new tech stack, while maintaining the functionality of the existing site – Implemented Jest unit tests on the front end and Mocha unit tests on the BE to ensure code quality',
    website: 'https://www.mapistry.com/',
    tags: [
      'JavaScript',
      'TypeScript',
      'React.js',
      'Styled Components',
      'MaterialUI',
      'React Query',
      'Jest',
      'Mocha',
      'Node.js',
    ],
  },
  {
    date: 'Jun 2020 - May 2022',
    company: 'Ready',
    description:
      "A healthcare startup that provides more easily accessible non-emergency healthcare by sending responders to a patient's home.",
    role: 'Front-end Software Engineer',
    details:
      'Implemented new features in the client facing side of the app used by responders, supervisors, and clinicians – Assisted in interviewing and evaluating 15+ candidates on technical screens – Implemented jest unit tests for new features – Transitioned the app on the front end from the original tech stack to a new tech stack',
    website: 'https://www.mylaurelhealth.com/',
    tags: [
      'JavaScript',
      'TypeScript',
      'Node.js',
      'React.js',
      'Apollo GraphQL',
      'Jest',
      'Styled Components',
      'Storybook',
    ],
  },
  {
    date: 'Apr 2020 - Jun 2020',
    company: 'Errunds',
    description:
      'An online community marketplace connecting the user to local brick and mortars.',
    role: 'Full-stack Developer Intern',
    details:
      'Implemented cart screen features through the full-stack – Contributed to new user signup and authentication - Contributed to the past orders screen',
    website: 'https://tyca.nyc/',
    tags: [
      'JavaScript',
      'Node.js',
      'React-Redux',
      'React Native',
      'Apollo GraphQL',
      'PostgreSQL',
      'Express.js',
      'Sequelize',
    ],
  },
];

export const architectureWorkItems = [
  {
    date: 'Sept 2017 - Dec 2018',
    company: 'Bade Stageberg Cox Architecture',
    role: 'Project Architect / Architectural Designer',
    description: `Supervised multiple construction phases for the relocation of Artists Space, an iconic NYC art gallery – Managed the renovation of a summer kitchen highly tailored to high-profile client’s requirements – Implemented diagrams, detailed sketches, and revised shop drawings – Illustrated concepts as 3D models and renderings – Involved in contractor, client, and consultant correspondence and coordination.`,
    website: 'https://www.bscarchitecture.com/',
    tags: [
      'AutoCad',
      'Illustrator',
      'Photoshop',
      'Sketch-up',
      'Vray',
      'Rhinoceros',
    ],
  },
  {
    date: 'Oct 2015 - Sept 2017',
    company: "O'Neill Rose Architects",
    role: 'Project Architect / Architectural Designer',
    description: `Managed multiple phases of single-family NYC residences – Developed and generated detailed drawings and sketches – Revised shop drawings – Generated 3D models, diagrams, and renderings – Involved in contractor, client, and consultant correspondence and coordination.`,
    website: 'https://www.oneillrosearchitects.com/',
    tags: [
      'AutoCad',
      'Illustrator',
      'Photoshop',
      'Sketch-up',
      'Vray',
      'Rhinoceros',
    ],
  },
  {
    date: 'Jun 2013 - Oct 2015',
    company: 'Audrey Matlock Architect',
    role: 'Project Architect / Architectural Designer',
    description: `Managed the Construction Administration phase for a single-family NYC apartment
– Organized and coordinated interior design work of an award-winning Hamptons residence – Developed design drawings and detailed drawings – Generated 3D models and renderings.`,
    website: 'http://www.audreymatlock.com/',
    tags: ['Vectorworks', 'Illustrator', 'Photoshop', 'Vray', 'Rhinoceros'],
  },
  {
    date: 'Nov 2011 - Apr 2013',
    company: 'Lauren Rubin Architecture',
    role: 'Architectural Designer',
    description: `Assisted in the construction administration phase of multiple single family residences
– Organized and coordinated interior design work for an advertising company and a single-family residence – Generated drawings for furniture placement – Generated 3D concept renderings of each room with – Created all phases of document sets for two single-family residences.`,
    website: 'https://laurenrubinarchitecture.com/',
    tags: ['AutoCad', 'Photoshop', 'Sketchup'],
  },
  {
    date: 'Jul 2009 - Apr 2010',
    company: 'Brillembourg Architects',
    role: 'Junior Architectural Designer',
    description:
      'Assisted in the development of a design proposal for a housing complex/hotel in Venezuela with 3D models, renderings, and 2D drawings – Assisted in all phases of design, development, and construction for a one bedroom Manhattan residential renovation, including the custom design of a dining table and lamp – Revised shop drawings and implemented detailed sketches.',
    website: 'https://www.carlosbrillembourgarchitects.com/',
    tags: ['AutoCad', 'Photoshop', 'Sketchup'],
  },
  {
    date: 'Sep 2007 - April 2009',
    company: 'Garrison Architects',
    role: 'Junior Architectural Designer',
    description:
      'Managed the Grand Army Plaza International Competition submission in Brooklyn, NY – Contributed to concept ideas, 3D models, renderings, and design drawings – Assisted in all phases of design and development for the US Consulate Residence in Samoa – Generated 3D Models, renderings, schematic design, design development, and construction documents',
    website: 'https://www.garrisonarchitects.com/',
    tags: [
      'AutoCad',
      'Photoshop',
      'Illustrator',
      'Sketchup',
      'Vray',
      'Maxwell Render',
    ],
  },
];

export const projects = [
  {
    title: 'Git Note',
    description:
      'A comprehensive knowledge repository for developers to document, track, and retrieve learnings, set learning goals, and visualize progress.',
    image: DevTodayImage,
    altText: 'git-note',
    route: '/projects/dev-today',
    tags: [
      'Next.js',
      'TypeScript',
      'Auth',
      'PostgreSQL',
      'Prisma ORM',
      'Supabase',
      'Tailwind CSS',
      'Shadcn',
      'TinyMCE',
    ],
  },
  {
    title: 'Dev Today',
    description:
      'A comprehensive content creation platform tailored for developers, featuring a feed of dev news, podcasts, and events, fostering community engagement and knowledge sharing',
    image: DevTodayImage,
    route: '/projects/dev-today',
    altText: 'dev-today',
    tags: [
      'Next.js',
      'TypeScript',
      'Clerk',
      'PostgreSQL',
      'Prisma ORM',
      'Supabase',
      'Tailwind CSS',
      'Shadcn',
      'TinyMCE',
    ],
  },
];

export const artImages = [
  {
    id: 1,
    src: ArmadilloTails,
    altText: 'armadillo-tails',
    title: 'Armadillo-esque',
    tags: ['black and white', 'pen on paper', 'sketchbook sketch'],
  },
  {
    id: 2,
    src: BenchLines,
    altText: 'bench-lines',
    title: 'An Unraveling',
    tags: ['black and white', 'pen on paper', 'sketchbook sketch'],
  },
  {
    id: 3,
    src: Clothesline,
    altText: 'clothesline',
    title: 'Busy Thoughts',
    tags: ['black and white', 'pen on paper', 'doodle'],
  },
  {
    id: 4,
    src: HouseLines,
    altText: 'house-lines',
    title: 'A House in Austin',
    tags: ['black and white', 'pen on paper', 'sketchbook sketch'],
  },
  {
    id: 5,
    src: ManWithWeeds,
    altText: 'man-with-weeds',
    title: 'In the Weeds',
    tags: ['black and white', 'pen on paper', 'sketchbook sketch'],
  },
  {
    id: 6,
    src: SpaceMan,
    altText: 'space-man',
    title: 'Tangled',
    tags: ['black and white', 'pen and pencil on paper', 'sketchbook sketch'],
  },
  {
    id: 7,
    src: SpaghettiPeople,
    altText: 'spaghetti-people',
    title: 'Wormholes',
    tags: ['black and white', 'pen on paper', 'sketchbook sketch'],
  },
  {
    id: 8,
    src: CrowsSelfPortrait,
    altText: 'crows-self-portrait',
    title: 'Overwhelmed',
    tags: [
      'black and white',
      'pen on paper',
      'copic markers',
      'sketchbook sketch',
    ],
  },
  {
    id: 9,
    src: SpillingOver,
    altText: 'spilling-over',
    title: 'Spilling Over',
    tags: ['pen on paper', 'sketchbook sketch'],
  },
  {
    id: 10,
    src: Beowolf,
    altText: 'beowolf',
    title: 'Book Cover: Beowulf',
    tags: ['photoshop', 'illustration', 'book cover idea'],
  },
  {
    id: 11,
    src: KingCrownDiamonds,
    altText: 'king-crown-diamonds',
    title: 'The King and his Diamonds',
    tags: [
      'pen on paper',
      'color pencil on paper',
      'sketchbook sketch',
      'photoshop',
    ],
  },
  {
    id: 12,
    src: Flowers,
    altText: 'flowers',
    title: "Flowers for Mother's Day",
    tags: ['pen on paper', 'experiments in watercolors'],
  },
  {
    id: 13,
    src: BleedingBlues,
    altText: 'bleeding-blues',
    title: 'Bleeding Blues',
    tags: ['pen on wood', 'gouache on wood'],
  },
  {
    id: 14,
    src: HeartSplatters,
    altText: 'heart-splatters',
    title: 'Heart Splatters',
    tags: ['pen on paper', 'gouache on paper', 'sketchbook sketch'],
  },
  {
    id: 15,
    src: Day2Spider,
    altText: 'day-2-spider',
    title: 'Sketch from Memory: Unnerved',
    tags: ['pen on paper', 'photoshop', 'memory sketch'],
  },
  {
    id: 16,
    src: Day4PipeWorms,
    altText: 'day-4-pipe-worms',
    title: 'Sketch from Memory: Burst',
    tags: ['pen on paper', 'photoshop', 'memory sketch'],
  },
  {
    id: 17,
    src: Day5CityMoon,
    altText: 'day-5-city-moon',
    title: 'Sketch from Memory: Nighttime Moonscape',
    tags: ['pen on paper', 'photoshop', 'memory sketch'],
  },
  {
    id: 18,
    src: MirrorMirror,
    altText: 'mirror-mirror',
    title: 'Is My Face Still There?',
    tags: ['pen on paper', 'photoshop', 'self portrait', 'illustration'],
  },
  {
    id: 19,
    src: Toothbrush,
    altText: 'toothbrush',
    title: "I Really Don't Want To",
    tags: ['pen on paper', 'photoshop', 'self portrait', 'illustration'],
  },
  {
    id: 20,
    src: TreesAndMountains,
    altText: 'trees-and-mountains',
    title: 'In the Darkened Hour by Bruce Boston',
    tags: ['pen on paper', 'photoshop', 'poem illustration'],
  },
  {
    id: 21,
    src: Curlew,
    altText: 'curlew',
    title: 'Curlew',
    tags: ['pen on paper', 'photoshop', 'illustration'],
  },
  {
    id: 22,
    src: LandscapeHand,
    altText: 'landscape-hand',
    title: 'Encroach',
    tags: ['pen on paper', 'photoshop', 'illustration'],
  },
  {
    id: 23,
    src: PhonesRamen,
    altText: 'phones-ramen',
    title: 'Deceit',
    tags: ['pen on paper', 'photoshop', 'illustration'],
  },
  {
    id: 24,
    src: CrowProcess,
    altText: 'crow-process',
    title: 'Process: Crow',
    tags: ['acrylics', 'process'],
  },
  {
    id: 25,
    src: Crow,
    altText: 'crow',
    title: 'Crow',
    tags: ['acrylics'],
  },
  {
    id: 26,
    src: AbstractFlowerProcess,
    altText: 'abstract-flower-process',
    title: 'Process: Abstract Flower',
    tags: ['gouache', 'process', 'hilma af klint inspired', 'abstract art'],
  },
  {
    id: 27,
    src: AbstractFlower,
    altText: 'abstract-flower',
    title: 'Abstract Flower',
    tags: ['gouache', 'hilma af klint inspired', 'abstract art'],
  },
  {
    id: 28,
    src: Jellyfish,
    altText: 'jellyfish',
    title: 'Process: Jellyfish',
    tags: ['gouache', 'process'],
  },
  {
    id: 29,
    src: Jellyfish2,
    altText: 'jellyfish-2',
    title: 'Jellyfish',
    tags: ['gouache'],
  },
  {
    id: 30,
    src: FlyingGeckoProcess,
    altText: 'flying-gecko-process',
    title: 'Process: Winged Gecko',
    tags: ['gouache', 'process', 'options'],
  },
  {
    id: 31,
    src: FlyingGecko,
    altText: 'flying-gecko',
    title: 'Process: Winged Gecko',
    tags: ['gouache'],
  },
  {
    id: 32,
    src: SelfPortraitPaint,
    altText: 'self-portrait-paint',
    title: 'Self-Portrait',
    tags: ['acrylics', 'self=portrait'],
  },
  {
    id: 33,
    src: ManLinesPaint,
    altText: 'man-lines-paint',
    title: 'Portrait of a Man',
    tags: ['acrylics', 'portrait', 'lines'],
  },
  {
    id: 34,
    src: ColoredTiles,
    altText: 'colored-tiles',
    title: 'Colored Tiles',
    tags: ['color pencils on paper', 'puerto rico inspired'],
  },
  {
    id: 35,
    src: ColorSplatsDots,
    altText: 'color-splats-dots',
    title: 'Color Splats with Dots',
    tags: ['gouache on wood', 'experiments on wood'],
  },
  {
    id: 36,
    src: ColorSplats,
    altText: 'color-splats',
    title: 'View 1: Disparate Thoughts in Color',
    tags: ['gouache on wood', 'experiments on wood', 'fluorescent colors'],
  },
  {
    id: 37,
    src: ColorSplats2,
    altText: 'color-splats-2',
    title: 'View 2: Disparate Thoughts in Color',
    tags: ['gouache on wood', 'experiments on wood', 'fluorescent colors'],
  },
  {
    id: 38,
    src: GlazedPlates,
    altText: 'glazed-plates',
    title: 'Glazed Handmade Plates',
    tags: ['ceramics', 'hand-built', 'glazed and fired'],
  },
  {
    id: 39,
    src: HatGlazeware2,
    altText: 'hat-glazeware-2',
    title: 'Glazed Hat Bowl',
    tags: ['ceramics', 'wheel-thrown', 'glazed and fired'],
  },
  {
    id: 40,
    src: BeehiveVase,
    altText: 'beehive-vase',
    title: 'Beehive Vase',
    tags: ['ceramics', 'wheel-thrown', 'fired', 'glazed interior'],
  },
  {
    id: 41,
    src: RamenGlazeware1,
    altText: 'ramen-glazeware-1',
    title: 'Bowl',
    tags: ['ceramics', 'wheel-thrown', 'glazed and fired'],
  },
  {
    id: 42,
    src: RamenGlazeware2,
    altText: 'ramen-glazeware-2',
    title: 'Ramen Bowl',
    tags: ['ceramics', 'wheel-thrown', 'glazed and fired'],
  },
  {
    id: 43,
    src: BubbleVase1,
    altText: 'bubble-vase-1',
    title: 'View 1: Bubble Vase',
    tags: [
      'ceramics',
      'hand-built',
      'glazed and fired',
      'experiments with glazes',
    ],
  },
  {
    id: 44,
    src: BubbleVase2,
    altText: 'bubble-vase-2',
    title: 'View 2: Bubble Vase',
    tags: [
      'ceramics',
      'hand-built',
      'glazed and fired',

      'experiments with glazes',
    ],
  },
  {
    id: 45,
    src: QuizzicalFigure,
    altText: 'quizzical-figure',
    title: 'Quizzical Figure',
    tags: ['ceramics', 'hand-built', 'greenware', 'figurine'],
  },
  {
    id: 46,
    src: UndulatingPlanter,
    altText: 'undulating-planter',
    title: 'Undulating Planter',
    tags: ['ceramics', 'hand-built', 'glazed and fired'],
  },
  {
    id: 47,
    src: WormVase,
    altText: 'worm-vase',
    title: 'Worm Vase',
    tags: [
      'ceramics',
      'hand-built',
      'glazed and fired',
      'experiments with glazes',
    ],
  },
  {
    id: 48,
    src: Mask1,
    altText: 'mask-1',
    title: 'View 1: Mask',
    tags: [
      'ceramics',
      'hand-built',
      'glazed and fired',
      'experiments with glazes',
    ],
  },
  {
    id: 49,
    src: Mask2,
    altText: 'mask-2',
    title: 'View 2: Mask',
    tags: [
      'ceramics',
      'hand-built',
      'glazed and fired',
      'experiments with glazes',
    ],
  },
  {
    id: 50,
    src: Agape,
    altText: 'agape',
    title: 'Agape Figure',
    tags: [
      'ceramics',
      'hand-built',
      'greenware',
      'figurine',
      'experiments with glazes',
    ],
  },
  {
    id: 51,
    src: LittleMan,
    altText: 'little-man',
    title: 'Greenware: Happy Little Dude',
    tags: ['ceramics', 'hand-built', 'greenware', 'figurine'],
  },
  {
    id: 52,
    src: LittleManGlazed,
    altText: 'little-man-glazed',
    title: 'Glazed: Happy Little Dude',
    tags: [
      'ceramics',
      'hand-built',
      'glazed and fired',
      'figurine',
      'experiments with glazes',
    ],
  },
  {
    id: 53,
    src: LoopyManProcess,
    altText: 'loopy-man-process',
    title: 'Greenware: Loopy Dude',
    tags: [
      'ceramics',
      'hand-built',
      'greenware',
      'figurine',
      'experiments with texture',
    ],
  },
  {
    id: 54,
    src: LoopyManGlazed3,
    altText: 'loopy-man-glazed-3',
    title: 'Glazed: Loopy Dude',
    tags: [
      'ceramics',
      'hand-built',
      'glazed and fired',
      'figurine',
      'experiments with glazes',
    ],
  },
];
