export const navbarItems = [
  {
    route: '/about',
    title: 'About',
  },
  {
    route: '/work',
    title: 'Work',
  },
  {
    route: '/projects',
    title: 'Projects',
  },
  {
    route: '/art',
    title: 'Art',
  },
];

export const workTabs = [
  {
    tabType: 'software',
    buttonText: 'Software Engineering',
  },
  {
    tabType: 'architecture',
    buttonText: 'Architecture',
  },
];

export const softwareWorkItems = [
  {
    date: 'Feb 2023 - May 2023',
    company: 'UStrive',
    role: 'Full-stack Developer',
    description:
      'Developed and maintained mentor and student portals for an online mentoring platform',
    website: 'https://ustrive.com/',
    tags: [
      'JavaScript',
      'Express',
      'Node.js',
      'React.js',
      'Axios',
      'Twilio',
      'Mixpanel',
      'Docker',
    ],
  },
  {
    date: 'May 2022 - Jan 2023',
    company: 'Mapistry',
    role: 'Full-stack Developer',
    description:
      'Contributed to the front end and back end of the application around dynamic form generation for internal and external use, as well as implemented the maintenance and migration of the existing functionality of the app, to the new site using updated UX/UI designs with the new React, React hooks, React Query, and Typescript tech stack.',
    website: 'https://www.mapistry.com/',
    tags: [
      'JavaScript',
      'TypeScript',
      'React.js',
      'Styled Components',
      'MaterialUI',
      'React Query',
      'Jest',
      'Mocha',
      'Node.js',
    ],
  },
  {
    date: 'Jun 2020 - May 2022',
    company: 'Ready',
    role: 'Front-end Software Engineer',
    description:
      'Worked on the client-facing app on the front-end team and have seen the app through from inception to production.',
    website: 'https://www.mylaurelhealth.com/',
    tags: [
      'JavaScript',
      'Express',
      'Node.js',
      'React.js',
      'Axios',
      'Twilio',
      'Mixpanel',
      'Docker',
    ],
  },
  {
    date: 'Apr 2020 - Jun 2020',
    company: 'Errunds',
    role: 'Full-stack Developer Intern',
    description:
      'Contributed to the client-facing side of the online community marketplace app.',
    website: 'https://tyca.nyc/',
    tags: [
      'JavaScript',
      'Express',
      'Node.js',
      'React.js',
      'Axios',
      'Twilio',
      'Mixpanel',
      'Docker',
    ],
  },
];

export const architectureWorkItems = [
  {
    date: 'Sept 2017 - Dec 2018',
    company: 'Bade Stageberg Cox Architecture',
    role: 'Project Architect / Architectural Designer',
    description: `Supervised multiple construction phases for the relocation of Artists Space, an iconic NYC art gallery – Managed the renovation of a summer kitchen highly tailored to high-profile client’s requirements – Implemented diagrams, detailed sketches, and revised shop drawings – Illustrated concepts as 3D models and renderings – Involved in contractor, client, and consultant correspondence and coordination.`,
    website: 'https://www.bscarchitecture.com/',
    tags: [
      'AutoCad',
      'Illustrator',
      'Photoshop',
      'Sketch-up',
      'Vray',
      'Rhinoceros',
    ],
  },
  {
    date: 'Oct 2015 - Sept 2017',
    company: "O'Neill Rose Architects",
    role: 'Project Architect / Architectural Designer',
    description: `Managed multiple phases of single-family NYC residences – Developed and generated detailed drawings and sketches – Revised shop drawings – Generated 3D models, diagrams, and renderings – Involved in contractor, client, and consultant correspondence and coordination.`,
    website: 'https://www.oneillrosearchitects.com/',
    tags: [
      'AutoCad',
      'Illustrator',
      'Photoshop',
      'Sketch-up',
      'Vray',
      'Rhinoceros',
    ],
  },
  {
    date: 'Jun 2013 - Oct 2015',
    company: 'Audrey Matlock Architect',
    role: 'Project Architect / Architectural Designer',
    description: `Managed the Construction Administration phase for a single-family NYC apartment
– Organized and coordinated interior design work of an award-winning Hamptons residence – Developed design drawings and detailed drawings – Generated 3D models and renderings.`,
    website: 'http://www.audreymatlock.com/',
    tags: ['Vectorworks', 'Illustrator', 'Photoshop', 'Vray', 'Rhinoceros'],
  },
  {
    date: 'Nov 2011 - Apr 2013',
    company: 'Lauren Rubin Architecture',
    role: 'Architectural Designer',
    description: `Assisted in the construction administration phase of multiple single family residences
– Organized and coordinated interior design work for an advertising company and a single-family residence – Generated drawings for furniture placement – Generated 3D concept renderings of each room with – Created all phases of document sets for two single-family residences.`,
    website: 'https://laurenrubinarchitecture.com/',
    tags: ['AutoCad', 'Photoshop', 'Sketchup'],
  },
  {
    date: 'Jul 2009 - Apr 2010',
    company: 'Brillembourg Architects',
    role: 'Junior Architectural Designer',
    description:
      'Assisted in the development of a design proposal for a housing complex/hotel in Venezuela with 3D models, renderings, and 2D drawings – Assisted in all phases of design, development, and construction for a one bedroom Manhattan residential renovation, including the custom design of a dining table and lamp – Revised shop drawings and implemented detailed sketches.',
    website: 'https://www.carlosbrillembourgarchitects.com/',
    tags: ['AutoCad', 'Photoshop', 'Sketchup'],
  },
  {
    date: 'Sep 2007 - April 2009',
    company: 'Garrison Architects',
    role: 'Junior Architectural Designer',
    description:
      'Managed the Grand Army Plaza International Competition submission in Brooklyn, NY – Contributed to concept ideas, 3D models, renderings, and design drawings – Assisted in all phases of design and development for the US Consulate Residence in Samoa – Generated 3D Models, renderings, schematic design, design development, and construction documents',
    website: 'https://www.garrisonarchitects.com/',
    tags: [
      'AutoCad',
      'Photoshop',
      'Illustrator',
      'Sketchup',
      'Vray',
      'Maxwell Render',
    ],
  },
];

export const artImages = [
  {
    id: 1,
    src: '/art/ArmadilloTails.jpg',
    altText: 'armadillo-tails',
    title: 'Armadillo-esque',
    tags: ['black and white', 'pen on paper', 'sketchbook sketch'],
  },
  {
    id: 2,
    src: '/art/BenchLines.jpg',
    altText: 'bench-lines',
    title: 'An Unraveling',
    tags: ['black and white', 'pen on paper', 'sketchbook sketch'],
  },
  {
    id: 3,
    src: '/art/Clothesline.jpg',
    altText: 'clothesline',
    title: 'Busy Thoughts',
    tags: ['black and white', 'pen on paper', 'doodle'],
  },
  {
    id: 4,
    src: '/art/HouseLines.jpg',
    altText: 'house-lines',
    title: 'A House in Austin',
    tags: ['black and white', 'pen on paper', 'sketchbook sketch'],
  },
  {
    id: 5,
    src: '/art/ManWithWeeds.jpg',
    altText: 'man-with-weeds',
    title: 'In the Weeds',
    tags: ['black and white', 'pen on paper', 'sketchbook sketch'],
  },
  {
    id: 6,
    src: '/art/SpaceMan.jpg',
    altText: 'space-man',
    title: 'Tangled',
    tags: ['black and white', 'pen and pencil on paper', 'sketchbook sketch'],
  },
  {
    id: 7,
    src: '/art/SpaghettiPeople.jpg',
    altText: 'spaghetti-people',
    title: 'Wormholes',
    tags: ['black and white', 'pen on paper', 'sketchbook sketch'],
  },
  {
    id: 8,
    src: '/art/CrowsSelfPortrait.jpg',
    altText: 'crows-self-portrait',
    title: 'Overwhelmed',
    tags: [
      'black and white',
      'pen on paper',
      'copic markers',
      'sketchbook sketch',
    ],
  },
  {
    id: 9,
    src: '/art/SpillingOver.jpg',
    altText: 'spilling-over',
    title: 'Spilling Over',
    tags: ['pen on paper', 'sketchbook sketch'],
  },
  {
    id: 10,
    src: '/art/Beowulf.jpg',
    altText: 'beowulf',
    title: 'Book Cover: Beowulf',
    tags: ['photoshop', 'illustration', 'book cover idea'],
  },
  {
    id: 11,
    src: '/art/KingCrownDiamonds.jpg',
    altText: 'king-crown-diamonds',
    title: 'The King and his Diamonds',
    tags: [
      'pen on paper',
      'color pencil on paper',
      'sketchbook sketch',
      'photoshop',
    ],
  },
  {
    id: 12,
    src: '/art/Flowers.jpg',
    altText: 'flowers',
    title: "Flowers for Mother's Day",
    tags: ['pen on paper', 'experiments in watercolors'],
  },
  {
    id: 13,
    src: '/art/BleedingBlues.jpg',
    altText: 'bleeding-blues',
    title: 'Bleeding Blues',
    tags: ['pen on wood', 'gouache on wood'],
  },
  {
    id: 14,
    src: '/art/HeartSplatters.jpg',
    altText: 'heart-splatters',
    title: 'Heart Splatters',
    tags: ['pen on paper', 'gouache on paper', 'sketchbook sketch'],
  },
  {
    id: 15,
    src: '/art/Day2Spider.jpg',
    altText: 'day-2-spider',
    title: 'Sketch from Memory: Unnerved',
    tags: ['pen on paper', 'photoshop', 'memory sketch'],
  },
  {
    id: 16,
    src: '/art/Day4Pipeworms.jpg',
    altText: 'day-4-pipe-worms',
    title: 'Sketch from Memory: Burst',
    tags: ['pen on paper', 'photoshop', 'memory sketch'],
  },
  {
    id: 17,
    src: '/art/Day5CityMoon.jpg',
    altText: 'day-5-city-moon',
    title: 'Sketch from Memory: Nighttime Moonscape',
    tags: ['pen on paper', 'photoshop', 'memory sketch'],
  },
  {
    id: 18,
    src: '/art/MirrorMirror.jpg',
    altText: 'mirror-mirror',
    title: 'Is My Face Still There?',
    tags: ['pen on paper', 'photoshop', 'self portrait', 'illustration'],
  },
  {
    id: 19,
    src: '/art/Toothbrush.jpg',
    altText: 'toothbrush',
    title: "I Really Don't Want To",
    tags: ['pen on paper', 'photoshop', 'self portrait', 'illustration'],
  },
  {
    id: 20,
    src: '/art/TreesAndMountains.jpg',
    altText: 'trees-and-mountains',
    title: 'In the Darkened Hour by Bruce Boston',
    tags: ['pen on paper', 'photoshop', 'poem illustration'],
  },
  {
    id: 21,
    src: '/art/Curlew.jpg',
    altText: 'curlew',
    title: 'Curlew',
    tags: ['pen on paper', 'photoshop', 'illustration'],
  },
  {
    id: 22,
    src: '/art/LandscapeHand.jpg',
    altText: 'landscape-hand',
    title: 'Encroach',
    tags: ['pen on paper', 'photoshop', 'illustration'],
  },
  {
    id: 23,
    src: '/art/PhonesRamen.jpg',
    altText: 'phones-ramen',
    title: 'Deceit',
    tags: ['pen on paper', 'photoshop', 'illustration'],
  },
  {
    id: 24,
    src: '/art/CrowProcess.jpg',
    altText: 'crow-process',
    title: 'Process: Crow',
    tags: ['acrylics', 'process'],
  },
  {
    id: 25,
    src: '/art/Crow.jpg',
    altText: 'crow',
    title: 'Crow',
    tags: ['acrylics'],
  },
  {
    id: 26,
    src: '/art/AbstractFlowerProcess.jpg',
    altText: 'abstract-flower-process',
    title: 'Process: Abstract Flower',
    tags: ['gouache', 'process', 'hilma af klint inspired', 'abstract art'],
  },
  {
    id: 27,
    src: '/art/AbstractFlower.jpg',
    altText: 'abstract-flower',
    title: 'Abstract Flower',
    tags: ['gouache', 'hilma af klint inspired', 'abstract art'],
  },
  {
    id: 28,
    src: '/art/Jellyfish.jpg',
    altText: 'jellyfish',
    title: 'Process: Jellyfish',
    tags: ['gouache', 'process'],
  },
  {
    id: 29,
    src: '/art/Jellyfish2.jpg',
    altText: 'jellyfish-2',
    title: 'Jellyfish',
    tags: ['gouache'],
  },
  {
    id: 30,
    src: '/art/FlyingGeckoProcess.jpg',
    altText: 'flying-gecko-process',
    title: 'Process: Winged Gecko',
    tags: ['gouache', 'process', 'options'],
  },
  {
    id: 31,
    src: '/art/FlyingGecko.jpg',
    altText: 'flying-gecko',
    title: 'Process: Winged Gecko',
    tags: ['gouache'],
  },
  {
    id: 32,
    src: '/art/SelfPortraitPaint.jpg',
    altText: 'self-portrait-paint',
    title: 'Self-Portrait',
    tags: ['acrylics', 'self=portrait'],
  },
  {
    id: 33,
    src: '/art/ManLinesPaint.jpg',
    altText: 'man-lines-paint',
    title: 'Portrait of a Man',
    tags: ['acrylics', 'portrait', 'lines'],
  },
  {
    id: 34,
    src: '/art/ColoredTiles.jpg',
    altText: 'colored-tiles',
    title: 'Colored Tiles',
    tags: ['color pencils on paper', 'puerto rico inspired'],
  },
  {
    id: 35,
    src: '/art/ColorSplatsDots.jpg',
    altText: 'color-splats-dots',
    title: 'Color Splats with Dots',
    tags: ['gouache on wood', 'experiments on wood'],
  },
  {
    id: 36,
    src: '/art/ColorSplats.jpg',
    altText: 'color-splats',
    title: 'View 1: Disparate Thoughts in Color',
    tags: ['gouache on wood', 'experiments on wood', 'fluorescent colors'],
  },
  {
    id: 37,
    src: '/art/ColorSplats2.jpg',
    altText: 'color-splats-2',
    title: 'View 2: Disparate Thoughts in Color',
    tags: ['gouache on wood', 'experiments on wood', 'fluorescent colors'],
  },
  {
    id: 38,
    src: '/art/GlazedPlates.jpg',
    altText: 'glazed-plates',
    title: 'Glazed Handmade Plates',
    tags: ['ceramics', 'hand-built', 'glazed and fired'],
  },
  {
    id: 39,
    src: '/art/HatGlazeware2.jpg',
    altText: 'hat-glazeware-2',
    title: 'Glazed Hat Bowl',
    tags: ['ceramics', 'wheel-thrown', 'glazed and fired'],
  },
  {
    id: 40,
    src: '/art/BeehiveVase.jpg',
    altText: 'beehive-vase',
    title: 'Beehive Vase',
    tags: ['ceramics', 'wheel-thrown', 'fired', 'glazed interior'],
  },
  {
    id: 41,
    src: '/art/RamenGlazeware1.jpg',
    altText: 'ramen-glazeware-1',
    title: 'Bowl',
    tags: ['ceramics', 'wheel-thrown', 'glazed and fired'],
  },
  {
    id: 42,
    src: '/art/RamenGlazeware2.jpg',
    altText: 'ramen-glazeware-2',
    title: 'Ramen Bowl',
    tags: ['ceramics', 'wheel-thrown', 'glazed and fired'],
  },
  {
    id: 43,
    src: '/art/BubbleVase1.jpg',
    altText: 'bubble-vase-1',
    title: 'View 1: Bubble Vase',
    tags: [
      'ceramics',
      'hand-built',
      'glazed and fired',
      'experiments with glazes',
    ],
  },
  {
    id: 44,
    src: '/art/BubbleVase2.jpg',
    altText: 'bubble-vase-2',
    title: 'View 2: Bubble Vase',
    tags: [
      'ceramics',
      'hand-built',
      'glazed and fired',

      'experiments with glazes',
    ],
  },
  {
    id: 45,
    src: '/art/QuizzicalFigure.jpg',
    altText: 'quizzical-figure',
    title: 'Quizzical Figure',
    tags: ['ceramics', 'hand-built', 'greenware', 'figurine'],
  },
  {
    id: 46,
    src: '/art/UndulatingPlanter.jpg',
    altText: 'undulating-planter',
    title: 'Undulating Planter',
    tags: ['ceramics', 'hand-built', 'glazed and fired'],
  },
  {
    id: 47,
    src: '/art/Wormvase.jpg',
    altText: 'worm-vase',
    title: 'Worm Vase',
    tags: [
      'ceramics',
      'hand-built',
      'glazed and fired',
      'experiments with glazes',
    ],
  },
  {
    id: 48,
    src: '/art/Mask1.jpg',
    altText: 'mask-1',
    title: 'View 1: Mask',
    tags: [
      'ceramics',
      'hand-built',
      'glazed and fired',
      'experiments with glazes',
    ],
  },
  {
    id: 49,
    src: '/art/Mask2.jpg',
    altText: 'mask-2',
    title: 'View 2: Mask',
    tags: [
      'ceramics',
      'hand-built',
      'glazed and fired',
      'experiments with glazes',
    ],
  },
  {
    id: 50,
    src: '/art/Agape.jpg',
    altText: 'agape',
    title: 'Agape Figure',
    tags: [
      'ceramics',
      'hand-built',
      'greenware',
      'figurine',
      'experiments with glazes',
    ],
  },
  {
    id: 51,
    src: '/art/LittleMan.jpg',
    altText: 'little-man',
    title: 'Greenware: Happy Little Dude',
    tags: ['ceramics', 'hand-built', 'greenware', 'figurine'],
  },
  {
    id: 52,
    src: '/art/LittleManGlazed.jpg',
    altText: 'little-man-glazed',
    title: 'Glazed: Happy Little Dude',
    tags: [
      'ceramics',
      'hand-built',
      'glazed and fired',
      'figurine',
      'experiments with glazes',
    ],
  },
  {
    id: 53,
    src: '/art/LoopyManProcess.jpg',
    altText: 'loopy-man-process',
    title: 'Greenware: Loopy Dude',
    tags: [
      'ceramics',
      'hand-built',
      'greenware',
      'figurine',
      'experiments with texture',
    ],
  },
  {
    id: 54,
    src: '/art/LoopyManGlazed3.jpg',
    altText: 'loopy-man-glazed-3',
    title: 'Glazed: Loopy Dude',
    tags: [
      'ceramics',
      'hand-built',
      'glazed and fired',
      'figurine',
      'experiments with glazes',
    ],
  },
];
